#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "[ term ]" "[ www ]" "[ sys ]" "[ dev ]" "[ misc ]"

###############################################################################################
## ----------------------------------- pretty basic configs -----------------------------------
###############################################################################################
bspc config border_width         4
bspc config window_gap          12
bspc config focused_border_color "#9F74F0"
bspc config normal_border_color "#908ABE"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


###############################################################################################
## --------------------------------- RULES, TO RULE THEM ALL ----------------------------------
###############################################################################################

# Atached desktop rules ---------------------------------------------

    # Rules cheatset examples
    #
    # 		bspc rule -a Gimp desktop='^8' state=floating follow=on
    # 		bspc rule -a mplayer2 state=floating
    # 		bspc rule -a Kupfer.py focus=on
    # 		bspc rule -a Screenkey manage=off
    #

# 1
bspc rule -a kitty desktop='^1' follow=on
bspc rule -a alacritty desktop='^1' follow=on

# 2
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on

# 3
bspc rule -a Pavucontrol desktop='^3' follow=on
bspc rule -a Thunar desktop='^3' follow=on

# 4
bspc rule -a Emacs desktop='^4' follow=on state=fullscreen


###############################################################################################
## ------------------------------------- external scripts -------------------------------------
###############################################################################################

bspc config external_rules_command ${HOME}/.config/bspwm/external_rules
${HOME}/.config/bspwm/autostart &
